[package]
name = "oscuro-core"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.12"
tracing = "0.1.37"
