name: "Test, build and push caches"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --accept-flake-config
      - uses: cachix/cachix-action@v14
        with:
          name: bonfire
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L --accept-flake-config
