name: nix-build-publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: nix-runner
    steps:
      - uses: actions/checkout@v4
      - run: nix flake check
      - uses: cachix/cachix-action@v14
        with:
          name: bonfire
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L 
